# Generated by Django 3.0.8 on 2020-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='NAME')),
                ('image', models.ImageField(default='', upload_to='static/img/profile', verbose_name='IMAGE')),
                ('tel', models.CharField(max_length=12, verbose_name='TEL')),
                ('email', models.EmailField(max_length=30, verbose_name='EMAIL')),
                ('birth', models.DateField(null=True, verbose_name='BIRTH')),
                ('tech', models.TextField(null=True, verbose_name='TECH')),
                ('intro', models.TextField(blank=True, default='안녕하세요', null=True, verbose_name='INTRO')),
                ('career', models.TextField(null=True, verbose_name='CAREER')),
                ('kakaoId', models.CharField(max_length=100, null=True, verbose_name='KAKAOID')),
                ('github_url', models.CharField(max_length=100, null=True, verbose_name='GITHUB')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='', max_length=200, verbose_name='PROJECT TITLE')),
                ('project_des', models.TextField(default='', verbose_name='PROJECT DESCRIPTION')),
                ('project_url', models.TextField(default='', verbose_name='PROJECT URL')),
                ('project_img', models.ImageField(default='', upload_to='static/img/project', verbose_name='PROJECT IMAGE')),
                ('project_id', models.IntegerField(default=0, null=True, verbose_name='PROJECT ID')),
            ],
        ),
    ]
