# Generated by Django 3.0.8 on 2020-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.TextField(blank=True)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('birth', models.TextField(blank=True)),
                ('tech', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True, default='안녕하세요')),
                ('career', models.TextField(blank=True)),
                ('kakaoId', models.TextField(blank=True)),
                ('github_url', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_des',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_img',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_title',
            field=models.CharField(default='', max_length=200, verbose_name='프로젝트 이름'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_url',
            field=models.TextField(default=''),
        ),
    ]
