# Generated by Django 3.0.8 on 2020-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.TextField(null=True, verbose_name='생년월일'),
        ),
    ]
