# Generated by Django 3.0.8 on 2020-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_img',
            field=models.ImageField(null=True, upload_to='myCareerApp/static/img/project', verbose_name='PROJECT IMAGE'),
        ),
    ]
