# Generated by Django 3.0.8 on 2020-08-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_id',
            field=models.AutoField(db_column='ProjectId', default=1, primary_key=True, serialize=False),
        ),
    ]
