# Generated by Django 3.0.8 on 2020-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0002_auto_20200812_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_img',
            field=models.ImageField(default='', upload_to='myCareerApp/static/img/project', verbose_name='PROJECT IMAGE'),
        ),
    ]
