# Generated by Django 3.0.8 on 2020-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0002_auto_20200812_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_title',
            field=models.CharField(default='', max_length=200, verbose_name='프로젝트 이름'),
        ),
    ]
