# Generated by Django 3.0.8 on 2020-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0002_auto_20200829_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_id',
            field=models.AutoField(db_column='ProjectId', primary_key=True, serialize=False),
        ),
    ]
