# Generated by Django 3.0.8 on 2020-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0003_auto_20200812_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_password',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='myCareerApp/static/img/profile', verbose_name='IMAGE'),
        ),
    ]
