# Generated by Django 3.0.8 on 2020-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0004_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='BIRTH'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.TextField(blank=True, null=True, verbose_name='CAREER'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GITHUB'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/img/profile', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kakaoId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KAKAOID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tech',
            field=models.TextField(blank=True, null=True, verbose_name='TECH'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='TEL'),
        ),
    ]
