# Generated by Django 3.0.8 on 2020-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0004_auto_20200812_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='EMAIL'),
        ),
    ]
