# Generated by Django 3.0.8 on 2020-08-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0004_auto_20200812_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='아이디'),
        ),
    ]
