# Generated by Django 3.0.8 on 2020-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0005_auto_20200812_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='생년월일'),
        ),
    ]
