# Generated by Django 3.0.8 on 2020-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0006_auto_20200812_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
    ]
