# Generated by Django 3.0.8 on 2020-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0007_auto_20200812_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='BIRTH'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.TextField(null=True, verbose_name='CAREER'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(max_length=100, null=True, verbose_name='GITHUB'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(null=True, verbose_name='PROFILE IMAGE'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, default='안녕하세요', null=True, verbose_name='INTRO'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kakaoId',
            field=models.CharField(max_length=100, null=True, verbose_name='KAKAOID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=10, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tech',
            field=models.TextField(null=True, verbose_name='TECH'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='TEL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_password',
            field=models.CharField(max_length=15, verbose_name='PASSWORD'),
        ),
    ]
