# Generated by Django 3.0.8 on 2020-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0008_auto_20200812_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_des',
            field=models.TextField(default='', verbose_name='PROJECT DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_id',
            field=models.IntegerField(default='', verbose_name='PROJECT ID'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_img',
            field=models.TextField(null=True, verbose_name='PROJECT IMAGE'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_title',
            field=models.CharField(default='', max_length=200, verbose_name='PROJECT TITLE'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project_url',
            field=models.TextField(default='', verbose_name='PROJECT URL'),
        ),
    ]
