# Generated by Django 3.0.8 on 2020-08-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0009_auto_20200812_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='project_id',
            field=models.IntegerField(default=0, null=True, verbose_name='PROJECT ID'),
        ),
    ]
