# Generated by Django 3.0.8 on 2020-08-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCareerApp', '0010_auto_20200812_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboard',
            name='users',
        ),
    ]
